name: mdamount
version: 1.0.7
homepage: https://github.com/marchdev-tk/mdamount
repository: https://github.com/marchdev-tk/mdamount
issue_tracker: https://github.com/marchdev-tk/mdamount/issues
description: march.dev amount library. Provides a new way to work with an amount. From highly flexible creation to rich data manipulation and stringification options.

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  meta: ^1.15.0
  decimal: ^3.0.2

dev_dependencies:
  flutter_lints: ^5.0.0
  test: ^1.25.7
