name: build

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
    
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v4

    - name: 'Setup Dart'
      uses: dart-lang/setup-dart@v1.6.0

    - name: 'Get Packages'
      run: dart pub get

    - name: 'Run tests'
      run: dart pub run test

    - name: Activate coverage package
      run: dart pub global activate coverage

    - name: Collect coverage in json
      run: dart --disable-service-auth-codes --enable-vm-service=8111 --pause-isolates-on-exit & nohup dart pub global run coverage:collect_coverage --port=8111 --out=coverage.json --wait-paused --resume-isolates

    - name: Convert coverage to lcov
      run: dart pub global run coverage:format_coverage --lcov --in=coverage.json --out=lcov.info --packages=.packages --report-on=lib

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.0.5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: unittests
        file: ./lcov.info
        name: codecov-mdamount

    - name: 'Dry Run Publishing'
      run: dart pub publish --dry-run

    - name: 'Publish Artifact'
      run: dart pub publish --force
